confirm_os_window_close 0
background #000000
foreground #ffffff
cursor #ffffff
background_opacity 0.5

window_padding_width 10
hide_window_decorations yes
tab_bar_style hidden
window_border_width 1pt
active_border_color #ffffff
inactive_border_color #444444
window_margin_width 1

color1 #880000
color9 #aa0000
